### ISSUE TITLE
Getting the classification accuracy

### ISSUE THREAD

**Issue by Zumbalamambo** [yctung/AndroidLibSvm#4]
How do I get the accuracy percentage of classification?

**Comment by yctung** [comment]
Hi,

Do you mean the accuracy of prediction? (I think it can be got by just comparing the predict results and your data, right?). If you mean the probability of classification. You can do this:

```

       // 4. make SVM train
        String svmTrainOptions = " -b 1 -t 2 ";
        jniSvmTrain(svmTrainOptions + dataTrainPath + modelPath);

        // 5. make SVM predict
        String svmPredictOptions = " -b 1 ";
        jniSvmPredict(svmPredictOptions + dataPredictPath + modelPath + outputPath);
```

Where the -b is the original option in LibSVM to get probability model
