### ISSUE TITLE
The format of the input dat

### ISSUE THREAD

**Issue by YjDai** [yctung/AndroidLibSVM#6]
@yctung @aravindGear4  What is the format of the input data when SVM training and predicting?Thanks?Is there an example?Such as  XX.txt ?

**Comment by senthilki** [comment]
The input is in LibSVM format.

please refer https://stackoverflow.com/questions/40436694/libsvm-data-preparation-excel-data-to-libsvm-format

**Comment by yctung** [comment]
Sorry for the late reply, I was in a trip out of US. @senthilki  is right, the format is the LibSVM format
